theme = "hyde-x"
baseurl = "http://biol548o.github.io/website"
languageCode = "en-us"
publishDir = "docs"
publishdir = "docs"
#disqusShortname = "your_disqus_shortname"

[author]
    name = "Dealing with Data"

[params]
  theme = "theme-base-0b"
  tagline = "BIOL548O"
  copyright = "Â© Andrew MacDonald 2017"
  highlight = "sunburst"
  home = "About this course"
  truncate = false

  # Hide estimated reading time for posts.
  # Default (if omitted) is false.
  hideReadingTime = true



